### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by aadityabhatia** [leoffx/chat-with-gpt#3]
Fairly simple since GitHub actions are already defined. Just need to enable the actions and ensure the correct configuration. This will allow substituting the old repo's image with this updated one and hopefully serve as a drop-in replacement.

**Comment by aadityabhatia** [comment]
Also ran into this issue while attempting to build the docker image locally:

```
Dockerfile:41                                                                                                                                                                                 
--------------------
  39 |     
  40 |     # Copy the rest of the application code into the working directory
  41 | >>> COPY ./server/src ./src
  42 |     
  43 |     RUN CI=true sh -c "cd /app && npm run start && rm -rf data"
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref beb7b92f-4002-4a79-9c20-ef87d3bd3877::ufchquwyr7id81094qo24x2ps: "/server/src": not found
```

**Comment by leoffx** [comment]
hey, sorry for the late reply, my notifications were off.

I had removed the server folder since I'm not using anything server side at https://chatwithgpt-app.web.app/

but I'm ok with having it in the repo in case you want to build it yourself. I've just restored it
